function(HYB_float_bytes_to_type bytes dest)
    if(bytes EQUAL 4)
        set(${dest} "float" PARENT_SCOPE)
        return()
    endif()
    if(bytes EQUAL 8)
        set(${dest} "double" PARENT_SCOPE)
        return()
    endif()

    message(FATAL "${bytes} bytes floating point is not supported yet.")
    return()

    if(bytes EQUAL 4)
        set(${dest} "void" PARENT_SCOPE)
        return()
    endif()
    if(bytes EQUAL 4)
        set(${dest} "void" PARENT_SCOPE)
        return()
    endif()
endfunction()